name: Build and Push Docker image to Docker Hub

on: push
jobs:
  build-image:
    name: Build Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          Username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: DockerFileFolder.dockerignore
          push: true
          tags: vhadas44/testdemo:latest
